#!/bin/sh

# super kludge (TM) build script to allow tslib + dm2 build just by toolchain

. ./BUILD_SETTINGS

if [ -e RELEASE_STRING -a -e ./configure.ac ]; then
	(sed s/REPLACE_DM_VERSION/`cat RELEASE_STRING`/g \
		configure.ac > configure.ac.sed_modifyed && \
		mv -f configure.ac.sed_modifyed configure.ac )
	echo "#define DM_SW_VERSION \"`cat RELEASE_STRING`\"" > \
		src/gta02_dm2_version.h
fi

if [ "$1" = "clean" -o "$1" = "distclean" ] ; then
	rm configure
	cd tslib-1.0
	make $1
	rm configure
	cd ..
	make $1
	rm -rf staging/*
	rm -f $TARBALL
	exit 0
fi

# stop problems coming from non-GNU malloc
export ac_cv_func_malloc_0_nonnull=yes

cd tslib-1.0
./build
if [ $? -ne 0 ] ; then
 exit $?
fi

cd ..

#if [ ! -e Makefile ] ; then
echo "# reconfiguring"
./autogen.sh

export PKG_CONFIG_PATH="$STAGING_DIR/usr/lib/pkgconfig/"

ls $PKG_CONFIG_PATH

./configure $DIST_CONFIGURE_OPTIONS \
	--enable-fb \
	--disable-x11 \
	--enable-static \
	--disable-shared \
	CFLAGS="-Wall -Werror -I$STAGING_DIR/usr/include -L$STAGING_DIR/usr/lib"
make -s clean 
#fi

make &&\
make -s install DESTDIR=`pwd`/staging

mkdir -p staging/etc

# /etc/startup compatability

rm -f staging/etc/startup
ln -sf /sbin/init staging/etc/startup

# override ts.conf
cp om-dm2-ts.conf staging/etc/ts.conf

# include data dir
cp data/*.state data/pointercal staging/etc

# initscript
mkdir -p staging/etc/rc3.d
cp data/S99dm2 staging/etc/rc3.d

# multimedia
mkdir -p staging/usr/share/dm2
cp data/*.wav staging/usr/share/dm2

# test_scripts
mkdir -p staging/home/root
cp	data/splash.gz \
	data/dialout \
	data/checkAP.awk \
	data/test_script \
	data/test-dialer \
	staging/home/root

# flashnor + dl_finalimg
mkdir -p staging/sbin
mkdir -p staging/usr/sbin
cp data/flashnor staging/sbin
chmod +x staging/sbin/flashnor
cp data/dl_finalimg staging/usr/sbin
chmod +x staging/usr/sbin/dl_finalimg
cp data/envedit staging/usr/sbin
chmod +x staging/usr/sbin/envedit
cp data/flashuboot staging/usr/sbin
chmod +x staging/usr/sbin/flashuboot
cp data/flashimage staging/usr/sbin
chmod +x staging/usr/sbin/flashimage
cp data/dynenv staging/usr/sbin
chmod +x staging/usr/sbin/dynenv
cp data/environment.prep staging/usr/sbin
chmod +x staging/usr/sbin/environment.prep

# correct executable
rm -f staging/home/root/dm2.bin
cd staging/home/root
ln -sf ../../usr/bin/dm2.bin dm2.bin
cd ../../..

# cook tarball
cd staging
tar czf ../$TARBALL .
cd ..

