#! /bin/sh
# was -e , exit on signals

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in

	pmu)       
  		case "$2" in
 
			get_battval)
					cat /sys/bus/i2c/devices/0-0073/battvolt
					;;
			
			charge_start)
					echo Y | i2cset 0 0x08 0x29 0x2f
					;;
			
			charge_stop)
					echo Y | i2cset 0 0x08 0x29 0x0
					;;

			get_time)
					echo "Time : "
					date +%Y%m%d%H%M 					
					;;

			*)
					echo "$1 [more option]"
					;;
		esac
		;;
	audio)

		case "$2" in
          	
		 detect)
			AUDIOFAIL=0
			i2cdetect -a -y 0 0x1a 0x1a | grep XX && AUDIOFAIL=1

			if [ $AUDIOFAIL == 0 ]; then
				echo "[Audio Detect]: OK" 
			else
				echo "[Audio Detect]: FAIL"
			fi	
			;;	
   		 play)        	     							          		
		       alsactl -f /home/root/asound.loud.state restore
	              	aplay /home/root/win.wav &
			;;		      				

  		 stop)
		
			kill -SIGHUP `ps | grep -i "aplay $/home/root/win.wav" | grep -v grep | awk '{print $1}'`
			alsactl -f /home/root/asound.quiet.state restore
			;;		

		   *)
			echo "$1 [more option]"
			;;

		esac
		;;

	 wifi)

		case "$2" in

			    on)	
				ifconfig eth0 up
				;;
	
			detect)
				FAIL=1
				iwconfig | grep eth0 && FAIL=0
				if [ $FAIL == 0 ] ; then
				 echo "[WiFi Detect]: OK" 
				else
				 echo "[WiFi Detect]: FAIL"
				fi
				;;

			scan)			
				iwlist eth0 scan | grep ESSID			
				;;

			setSSID)

                                LOG=/tmp/wifi_log

				killall -q udhcpc

				echo "Scanning..."
				echo "Scanning..." >/tmp/wlan-progress
                                iwlist eth0 scan | awk -f /home/root/checkAP.awk | sort -n | head -n1 > /tmp/apname
				apname=
				if test -f /tmp/apname ; then
					apname=`cat /tmp/apname`
				fi

				APMAC=`echo $apname | cut -d' ' -f3`
				APNAME=`echo $apname | cut -d' ' -f2`

				echo setSSID: $APNAME $APMAC
				if test ! -z $APMAC  ; then
					echo "Associating to \"$APNAME\" / $APMAC" >>/tmp/wlan-progress
                                	iwconfig eth0 essid "$APNAME"
#                                	iwconfig eth0 ap $APMAC
					if [ $? -ne 0 ] ; then
						echo "FAIL assoc \"$APNAME\"" >>/tmp/wlan-progress
						ifconfig eth0 down
						iwconfig eth0 essid off
						exit 1
					fi
					echo "Associated, trying DHCP" >>/tmp/wlan-progress
                                	udhcpc --interface=eth0
					if [ -z "`ifconfig eth0 | grep inet`" ] ; then
						echo "FAIL DHCP" >>/tmp/wlan-progress
						killall -q udhcpc
						ifconfig eth0 down
						iwconfig eth0 essid off
						exit 1
					fi
					echo "Trying iperf" >>/tmp/wlan-progress
					iperf -c 192.168.1.22 -i 2 -b 11M -u -n 6M -t 4| \
						grep 2.0 | grep 4.0 | sed "s/^.*\ sec//g" > $LOG
					if [ -z "`cat $LOG`" ] ; then
						echo "FAIL iperf" >>/tmp/wlan-progress
						killall -q udhcpc
						ifconfig eth0 down
						iwconfig eth0 essid off
						rm -f /etc/resolv.conf
						exit 1
					fi
					echo "SUCCESS iperf" >>/tmp/wlan-progress
					cat $LOG >>/tmp/wlan-progress
                                        killall -q udhcpc
                                        ifconfig eth0 down
					iwconfig eth0 essid off
					rm -f /etc/resolv.conf
				else
					echo "[WiFi setSSID FAIL]"
					echo "FAILED to find AP" >>/tmp/wlan-progress
				fi
				;;
			off)
				ifconfig eth0 down
				;;
	  		*)
			      echo "$1 [more option]"
			      ;;

		esac
		;;
      hdq)

                case "$2" in
			detect)
				echo "voltage : "
cat  /sys/devices/platform/bq27000-battery.0/power_supply\:bat/voltage_now
echo "current : "
cat /sys/devices/platform/bq27000-battery.0/power_supply\:bat/current_now
echo "temperature : "
cat /sys/devices/platform/bq27000-battery.0/power_supply\:bat/temp
echo "capacity : "
cat /sys/devices/platform/bq27000-battery.0/power_supply\:bat/capacity
echo "charge : "
cat /sys/devices/platform/bq27000-battery.0/power_supply\:bat/charge_full
				;;
			*)
				echo "$1 [more option]"
				;;
                esac
                ;;
      off)

	      sync
		
     	      kill -9  `ps | grep dm2 | awk '{print $1}'`
	      kill -9  `ps | grep dm2 | awk '{print $1}'`	   
                ;;

	*)
		echo "[more option]"
		;;	
esac
exit 0

